# Generated by Django 3.2.9 on 2021-12-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('generation_time_stamp', models.IntegerField()),
                ('voltage_rms', models.FloatField()),
                ('current_rms', models.FloatField()),
                ('voltage_peak', models.FloatField()),
                ('current_peak', models.FloatField()),
                ('phase', models.FloatField()),
                ('voltage_frequency', models.FloatField()),
                ('average_power', models.FloatField()),
                ('energy_consumption', models.FloatField()),
                ('delete_status', models.BooleanField()),
            ],
        ),
    ]
